[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    ESP Async WebServer
    AsyncTCP
    ArduinoJson
    bblanchon/ArduinoJson @ ^6.21.3
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DBOARD_HAS_PSRAM
